services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./schema:/schema

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    env_file:
      - ./.env

  redis:
    image: redis
    container_name: redis
    # https://stackoverflow.com/a/72593084
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
